version: '3.9'

services:
  static-file-server:
    image: halverneus/static-file-server
    volumes:
      - "../web:/web"

  warp-socks:
    build: https://github.com/ainbr/Docker-Warp-Socks.git#problem2
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.conf.all.src_valid_mark: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "https://www.cloudflare.com/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 5

  curl:
    build: https://github.com/flrngel/curl-docker.git
